FROM elrey741/ansible-playbook
LABEL maintainer="Alex (elrey741) <dockerfile-social-contact@elrey741.33mail.com>"

RUN pip install --no-cache-dir --no-compile awscli

ENTRYPOINT [ "ansible-playbook" ]
